# Generated by Django 3.1.3 on 2020-12-01 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(db_column='AUTHOR_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='FIRST_NAME', max_length=511, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LAST_NAME', max_length=511, null=True)),
                ('about', models.CharField(blank=True, db_column='ABOUT', max_length=8191, null=True)),
            ],
            options={
                'db_table': 'AUTHOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('binding_id', models.AutoField(db_column='BINDING_ID', primary_key=True, serialize=False)),
                ('binding_type', models.CharField(blank=True, db_column='BINDING_TYPE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'BINDING',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(db_column='BOOK_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='TITLE', max_length=4096, null=True)),
                ('publication_date', models.IntegerField(blank=True, db_column='PUBLICATION_DATE', null=True)),
                ('synopsis', models.TextField(blank=True, db_column='SYNOPSIS', null=True)),
            ],
            options={
                'db_table': 'BOOK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('copy_id', models.AutoField(db_column='COPY_ID', primary_key=True, serialize=False)),
                ('language_id', models.IntegerField(blank=True, db_column='LANGUAGE_ID', null=True)),
                ('has_jacket', models.IntegerField(blank=True, db_column='HAS_JACKET', null=True)),
                ('edition', models.CharField(blank=True, db_column='EDITION', max_length=511, null=True)),
                ('isbn_10', models.CharField(blank=True, db_column='ISBN_10', max_length=10, null=True)),
                ('isbn_13', models.CharField(blank=True, db_column='ISBN_13', max_length=13, null=True)),
                ('price', models.DecimalField(blank=True, db_column='PRICE', decimal_places=0, max_digits=10, null=True)),
                ('descr', models.CharField(blank=True, db_column='DESCR', max_length=4096, null=True)),
                ('signed', models.IntegerField(blank=True, db_column='SIGNED', null=True)),
            ],
            options={
                'db_table': 'COPY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(db_column='GRADE_ID', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='LABEL', max_length=20, null=True)),
            ],
            options={
                'db_table': 'GRADE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(db_column='LANGUAGE_ID', primary_key=True, serialize=False)),
                ('language_code', models.CharField(blank=True, db_column='LANGUAGE_CODE', max_length=2, null=True)),
            ],
            options={
                'db_table': 'LANGUAGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(db_column='PUBLISHER_ID', primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(blank=True, db_column='PUBLISHER_NAME', max_length=511, null=True)),
            ],
            options={
                'db_table': 'PUBLISHER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WrittenBy',
            fields=[
                ('book', models.OneToOneField(db_column='BOOK_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='books.book')),
            ],
            options={
                'db_table': 'WRITTEN_BY',
                'managed': False,
            },
        ),
    ]
