-- Report 1
SELECT 
  A.FIRST_NAME, 
  A.LAST_NAME, 
  (
    SELECT COUNT(*)
    FROM BOOK AS B, WRITTEN_BY AS WB 
    WHERE WB.BOOK_ID = B.BOOK_ID AND WB.AUTHOR_ID = A.AUTHOR_ID
  ) AS NUM_BOOKS
FROM AUTHOR AS A;

-- Report 2 (TODO)
-- the following is untested
-- SELECT AUTHOR.FIRST_NAME, AUTHOR.LAST_NAME, BOOK.TITLE, COUNT(DISTINCT(BOOK.BOOK_ID)))
-- FROM AUTHOR, BOOK, WRITTEN_BY
-- WHERE WRITTEN_BY.BOOK_ID = BOOK.BOOK_ID
--       AND WRITTEN_BY.AUTHOR_ID = AUTHOR.AUTHOR_ID
-- GROUP BY BOOK.TITLE
-- ORDER BY AUTHOR.LAST_NAME;

-- Report 3 (TODO)
-- the following is untested
-- SELECT PUBLISHER.PUBLISHER_NAME, COUNT(DISTINCT(BOOK.ID))
-- FROM PUBLISHER, BOOK, COPY
-- WHERE PUBLISHER.PUBLISHER_ID = COPY.PUBLISHER_ID
--       AND COPY.BOOK_ID = BOOK.BOOK_ID;

-- Report 4 (TODO)
-- the following is untested
-- SELECT BOOK.TITLE
-- FROM BOOK, COPY
-- WHERE BOOK.BOOK_ID = COPY.BOOK_ID
--   AND --add columns
