DROP DATABASE IF EXISTS book_collection;
CREATE DATABASE book_collection;

USE book_collection;

CREATE TABLE PUBLISHER (
  PUBLISHER_ID INT AUTO_INCREMENT,
  PUBLISHER_NAME VARCHAR(50), -- Column F
  CONSTRAINT PUBLISHER_PK PRIMARY KEY (PUBLISHER_ID)
);

CREATE TABLE BOOK (
  BOOK_ID INT AUTO_INCREMENT,
  TITLE VARCHAR(4096), -- Column B
  PUBLISHER_ID INT,
  PUBLICATION_DATE YEAR, -- Column E
  SYNOPSIS VARCHAR(4096), -- choose one of the many / Column O
  CONSTRAINT BOOK_PK PRIMARY KEY (BOOK_ID),
  CONSTRAINT COPY_PUBLISHER_FK FOREIGN KEY (PUBLISHER_ID)
  REFERENCES PUBLISHER(PUBLISHER_ID)
);

CREATE TABLE AUTHOR (
  AUTHOR_ID INT AUTO_INCREMENT,
  FIRST_NAME VARCHAR(20), -- Column C
  LAST_NAME VARCHAR(20), -- Column C
  ABOUT VARCHAR(4096), -- choose one of the many / Column P
  CONSTRAINT AUTHOR_PK PRIMARY KEY (AUTHOR_ID)
);

CREATE TABLE GRADE (
  GRADE_ID INT AUTO_INCREMENT,
  LABEL VARCHAR(20), -- Column I
  CONSTRAINT GRADE_PK PRIMARY KEY (GRADE_ID)
);

CREATE TABLE BINDING (
  BINDING_ID INT AUTO_INCREMENT,
  BINDING_TYPE VARCHAR(50), -- Column D
  CONSTRAINT BINDING_PK PRIMARY KEY (BINDING_ID)
);

CREATE TABLE COPY (
  COPY_ID INT AUTO_INCREMENT, -- Column A
  BOOK_ID INT,
  BINDING_ID INT,
  GRADE_ID INT,
  HAS_JACKET BOOL,
  EDITION VARCHAR(255), -- Column L
  ISBN_10 CHAR(10), -- Column G
  ISBN_13 CHAR(13), -- Column H
  PRICE DECIMAL, -- Column M
  DESCR VARCHAR(4096), -- Column N
  SIGNED BOOLEAN, -- Column K
  CONSTRAINT COPY_PK PRIMARY KEY (COPY_ID),
  CONSTRAINT COPY_BOOK_FK FOREIGN KEY (BOOK_ID)
  REFERENCES BOOK(BOOK_ID),
  CONSTRAINT COPY_BINDING_FK FOREIGN KEY (BINDING_ID)
  REFERENCES BINDING(BINDING_ID),
  CONSTRAINT COPY_GRADE_FK FOREIGN KEY (GRADE_ID)
  REFERENCES GRADE(GRADE_ID)
);

CREATE TABLE WRITTEN_BY (
  BOOK_ID INT,
  AUTHOR_ID INT,
  CONSTRAINT WRITTEN_BY_PK PRIMARY KEY (BOOK_ID, AUTHOR_ID),
  CONSTRAINT WRITTEN_BY_AUTHOR_FK FOREIGN KEY (AUTHOR_ID)
  REFERENCES AUTHOR(AUTHOR_ID),
  CONSTRAINT WRITTEN_BY_BOOK_FK FOREIGN KEY (BOOK_ID)
  REFERENCES BOOK(BOOK_ID)
);